#!/bin/sh

set -e

cd ${HOME}/.system/ && git submodule update --init --recursive

if [ ! -f ~/.tmux.conf ]; then
    ln -s ${HOME}/.system/tmux.conf ${HOME}/.tmux.conf
fi

if [ ! -f ~/.zshrc ]; then
    ln -s ${HOME}/.system/zshrc ${HOME}/.zshrc
fi

STANDARD_LINKS=nvim kitty dunst eww kitty leftwm picom

for link in ${STANDARD_LINKS}; do
  if [ ! -d "${HOME}/.config/${link}" ]; then
    echo "Setting ${link} config."
    ln -s ${HOME}/.system/${link} ${HOME}/.config/${link}
  fi
done

if ! command -v nvim &> /dev/null; then
    echo "NOTE: You should install neovim real soon now."
fi
