#!/bin/sh

set -e

cd ${HOME}/.system/ && git submodule update --init --recursive

if [ ! -f ~/.tmux.conf ]; then
    ln -s ${HOME}/.system/tmux.conf ${HOME}/.tmux.conf
fi

if [ ! -f ~/.zshrc ]; then
    ln -s ${HOME}/.system/zshrc ${HOME}/.zshrc
fi

if [ ! -d ~/.config/nvim ]; then
    ln -s ${HOME}/.system/nvim ${HOME}/.config/nvim
fi

if [ ! -d ~/.config/kitty ]; then
    ln -s ${HOME}/.system/kitty ${HOME}/.config/kitty
fi

if ! command -v nvim &> /dev/null; then
    echo "NOTE: You should install neovim real soon now."
fi
