# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };

    kernelModules = [ "kvm-amd" ];
    loader.efi.canTouchEfiVariables = true;
    loader.systemd-boot = {
      enable = true;
      configurationLimit = 5;
    };
    extraModulePackages = [ ];
    supportedFilesystems = [ "zfs" ];
    zfs = {
      forceImportRoot = false;
      extraPools = [ "pool0" ];
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9927b20a-49a8-45b1-a49f-ef326a0b0f95";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/627A-A21E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/11c6d9cc-e36c-4747-8037-e91f35f196c0"; }
  ];

  nix.gc.automatic = true;
  nix.settings.auto-optimise-store = true;
  nix.gc.options = "--delete-older-than 30d";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.amdgpu.opencl.enable = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics = {
    enable = true;
    #    extraPackages = with pkgs; [
    #      rocmPackages.clr.icd
    #    ];
  };
  #  systemd.tmpfiles.rules = [
  #      "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  #  ];
}
